05 Timer
ananastasiap/balconies-glazing pull request #5
Opened 2023-04-13 09:37 UTC by ananastasiap

2023-04-13 09:43 UTC, ananastasiap commented on src/js/modules/timer.js
> +    const timeInterval = setInterval(updateClock, 1000);
В уроке `const timeInterval...` и `updateСlock()` располагались сразу же после `const seconds = timer.querySelector('#seconds');` но у меня таймер совсем не запускался. В итоге, решила передвинуть их в эту часть кода, и всё заработало.

2023-04-13 10:11 UTC, andrey-kudinov requested changes

2023-04-13 10:11 UTC, andrey-kudinov commented on src/js/main.js
> +  let deadline = '2023-10-01';
`const`

2023-04-13 10:11 UTC, andrey-kudinov commented on src/js/modules/timer.js
> +  };
перепиши пж в 1 строку с использованием тернарника

2023-04-13 10:11 UTC, andrey-kudinov commented on src/js/modules/timer.js
> +    };
короткий синтаксис

2023-04-16 10:09 UTC, andrey-kudinov commented on src/js/modules/draft.js
> +    const days = remainingTime.toLocaleDateString('ru-RU', { dateStyle: 'short' })
const [days] = ...

2023-04-16 10:10 UTC, andrey-kudinov commented on src/js/main.js
https://codepen.io/AndreyKudinov/pen/VwEaLaO?editors=1011

2023-04-16 21:17 UTC, ananastasiap commented on src/js/modules/timer.js
> +    const [hours, minutes, seconds] = remainingTime.toLocaleTimeString('ru-RU', { timeStyle: 'medium' }).split(':');
До меня наконец-то дошло, что я упустила месяцы. Насколько я понимаю, мне показывались всё время дни одного месяца, поэтому больше 31-го дня до дэдлайна мне таймер не выдавал (хотя я ставила и 2024 год, и 2025).

Я решила получить полное кол-во месяцев, а затем умножить их на дни, НО здесь погрешность, т.к. не во всех месяцах 30 дней. Пока не могу понять, как получить дни с помощью toLocaleDateString так, чтобы учитывалось количество месяцев. Или как, получив кол-во месяцев, можно было их перевести в кол-во дней

2023-04-17 11:21 UTC, andrey-kudinov commented on src/js/modules/timer.js
> +    const days = remainingTime.getUTCDate() + (totalMonths * 30); // умножаем количество месяцев на среднее количество дней
const daysLeft = Math.floor(remainingTime / (1000 * 60 * 60 * 24));

2023-04-17 11:21 UTC, andrey-kudinov commented on src/js/modules/timer.js
> +    const totalMonths = (remainingTime.getUTCFullYear() - 1970) * 12 + remainingTime.getUTCMonth();
Думаю тогда можно удалить

2023-04-17 21:12 UTC, merged